name: emulate Pipeline

on:
  push:
    branches:
      - "main"
      - "feature/*"
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: Lint 
        run: npm run eslint 
      - name: Unit tests
        run: npm test
      - name : E2E tests
        uses: cypress-io/github-action@v4
        with: 
          command: npm run test:2e2
          start: npm run dev
          wait-on: http://localhost:5000